### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by yogamurthy** [pdavies011010/atom-xmlvalidate#5] opened 2017-08-17 18:57 UTC
`Installing “atom-xmlvalidate@0.2.0” failed.Hide output…

> libxmljs-mt@0.16.1 install C:\Users\YSATHY~1\AppData\Local\Temp\apm-install-dir-117717-12364-11cd66q.z7ndrc0udi\node_modules\atom-xmlvalidate\node_modules\libxmljs-mt
> node-gyp rebuild

C:\Users\YSATHY~1\AppData\Local\Temp\apm-install-dir-117717-12364-11cd66q.z7ndrc0udi\node_modules\atom-xmlvalidate\node_modules\libxmljs-mt>if not defined npm_config_node_gyp (node "C:\Users\ysathy001c\AppData\Local\atom\app-1.19.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\ysathy001c\AppData\Local\atom\app-1.19.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\YSATHY~1\AppData\Local\Temp\apm-install-dir-117717-12364-11cd66q.z7ndrc0udi
`-- (empty)

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\ysathy001c\AppData\Local\Programs\Python\Python36-32\python.EXE" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\ysathy001c\AppData\Local\atom\app-1.19.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\ysathy001c\AppData\Local\atom\app-1.19.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\ysathy001c\\AppData\\Local\\atom\\app-1.19.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\ysathy001c\\AppData\\Local\\atom\\app-1.19.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\YSATHY~1\AppData\Local\Temp\apm-install-dir-117717-12364-11cd66q.z7ndrc0udi\node_modules\atom-xmlvalidate\node_modules\libxmljs-mt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\YSATHY~1\AppData\Local\Temp\apm-install-dir-117717-12364-11cd66q.z7ndrc0udi\package.json'
npm WARN apm-install-dir-117717-12364-11cd66q.z7ndrc0udi No description
npm WARN apm-install-dir-117717-12364-11cd66q.z7ndrc0udi No repository field.
npm WARN apm-install-dir-117717-12364-11cd66q.z7ndrc0udi No README data
npm WARN apm-install-dir-117717-12364-11cd66q.z7ndrc0udi No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\ysathy001c\\AppData\\Local\\atom\\app-1.19.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\ysathy001c\\AppData\\Local\\atom\\app-1.19.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\ysathy001c\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\ysathy001c\\.atom\\.apmrc" "install" "C:\\Users\\YSATHY~1\\AppData\\Local\\Temp\\d-117717-12364-1auy1oy.7qvd8fflxr\\package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! libxmljs-mt@0.16.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs-mt@0.16.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs-mt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs-mt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs-mt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\YSATHY~1\AppData\Local\Temp\apm-install-dir-117717-12364-11cd66q.z7ndrc0udi\npm-debug.log
npm ERR! code 1
`

**Comment by pdavies011010** [comment] 2017-08-17 19:27
Hi @yogamurthy  
    Please see the README, specifically there are some comments about build dependencies and a link in there about node-gyp. The issue is that node-gyp requires Python 2 (it cannot be built using Python 3). Closing this issue. 
Thanks,
Phill

**Closed as completed by pdavies011010** 2017-08-17 19:27 UTC
